### ISSUE TITLE
Missing `wake.mat` and `sleep.mat` files

### ISSUE THREAD

**Issue by fdeage** [iTCf/PCIcalc#1]
Hi,
I'm trying to run the PCI notebook but the two Matlab files seem missing. Is there any way to find them?

**Comment by ezemikulan** [comment]
Hi, sorry about the delay. @thierrynieus do you know where is the data?

**Comment by fdeage** [comment]
Thanks @ezemikulan for the reply, but in the meantime I found another PCI notebook :)

**Comment by thierrynieus** [comment]
Hi,
I just noticed the mat files are indeed missing, though they were part of
the corresponding hbp collab.
I can try to retrieve them from my backups and/or see if I can still
access the old hbp collab.
However if you are now on a new notebook it is ok. Be aware that some
notebooks (not the one released from Massimini's lab) may contain bugs
(e.g. wrong normalization, incorrect LZ78 algorithm, complexity is computed
with LZ77 and the two yield remarkable differences).
Best

**Comment by fdeage** [comment]
Thanks.
I found a piece of code called `PCI_v2`, at `https://gitlab.ebrains.eu/kancourt/tvb-adex-showcase3-git/-/blob/master/pci_v2.py`, which includes the `sort_binJ` and `source_entropy` functions.

**Comment by thierrynieus** [comment]
Hi Felix,
I have now:
1) provided a link to the wake.mat and sleep.mat (500 MB too much for
github)
2) added some lines in the readme file to redirect anyone to the more
recent examples we released for the Human Brain Project (SGA2).
https://github.com/thierrynieus/PerturbationalComplexityIndex
The PCI_v2 file is ok, you can go with it!
Best
Thierry

**Comment by fdeage** [comment]
Hi Thierry, sounds perfect, thanks!
